# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20170924_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
    ]
